-- 000001: shared extensions, helper functions and conventions.
--
-- Conventions applied across every migration in this directory:
--   * Surrogate keys are UUIDs generated by gen_random_uuid().
--   * Timestamps are TIMESTAMPTZ stored in UTC.
--   * Mutable rows carry updated_at, maintained by the set_updated_at trigger.
--   * Soft deletes use deleted_at; all read paths filter on deleted_at IS NULL.
--   * Ownership columns reference the external identity provider's subject ID
--     and are therefore TEXT rather than a local FK to a users table.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Maintains updated_at on every mutable table.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attaches the set_updated_at trigger to a table.
CREATE OR REPLACE FUNCTION attach_updated_at_trigger(target regclass) RETURNS void AS $$
BEGIN
    EXECUTE format(
        'CREATE TRIGGER %I BEFORE UPDATE ON %s FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
        'trg_' || TG_TABLE_NAME || '_set_updated_at',
        target
    );
END;
$$ LANGUAGE plpgsql;
